import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SubstrateProvider } from "@/contexts/useSubstrateContext";
import "@/app/globals.css";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
className={inter.className}
      >
        <SubstrateProvider>
          

          {children}
        </SubstrateProvider>
      </body>
    </html>
  );
}
